PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS users (
  userId INTEGER PRIMARY KEY AUTOINCREMENT,
  password TEXT NOT NULL,
  username TEXT NOT NULL UNIQUE,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  verified INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS groups (
  groupId INTEGER PRIMARY KEY AUTOINCREMENT,
  groupName TEXT NOT NULL,
  frequentItems TEXT NOT NULL DEFAULT '[]',
  favouriteItems TEXT NOT NULL DEFAULT '[]',
  groupChores TEXT NOT NULL DEFAULT '[]',
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS user_groups (
  userId INTEGER NOT NULL,
  groupId INTEGER NOT NULL,
  role TEXT NOT NULL,
  joinedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (groupId, userId),
  FOREIGN KEY (userId) REFERENCES users(userId) ON DELETE CASCADE,
  FOREIGN KEY (groupId) REFERENCES groups(groupId) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS events (
  eventId INTEGER PRIMARY KEY AUTOINCREMENT,
  groupId INTEGER NOT NULL,
  eventName TEXT NOT NULL,
  shoppingList TEXT NOT NULL DEFAULT '[]',
  itemList TEXT NOT NULL DEFAULT '[]',
  status TEXT NOT NULL,
  createdBy INTEGER,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (groupId) REFERENCES groups(groupId) ON DELETE CASCADE,
  FOREIGN KEY (createdBy) REFERENCES users(userId) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS refresh_tokens (
  tokenId INTEGER PRIMARY KEY AUTOINCREMENT,
  userId INTEGER NOT NULL,
  token TEXT NOT NULL,
  expiresAt DATETIME NOT NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (userId) REFERENCES users(userId) ON DELETE CASCADE
);